### ISSUE TITLE
Does the tool allow you to compare positions?

### ISSUE THREAD

**Issue by alanent** [broskicodes/chess-position-embeddings#1]
Hello, thanks for your work! I tried to train a model on 1M positions but the similarity measure does not return similar positions. Have you noticed this too?

**Comment by broskicodes** [comment]
hey Alan. thanks for reaching out!

tbh, i only spent a couple days on this project, so i didn't do a lot of testing.

in general I found that the top 1 or 2 similarity results are pretty good, but beyond that it is inconsistent.

Ex:
![image](https://github.com/user-attachments/assets/986af38a-7655-467a-bdfc-b76e1df61998)
![image](https://github.com/user-attachments/assets/e03e522c-503a-41d1-93cb-bedbf23c0e94)

i believe i trained the model on abt 50k positions.

im curious to know how u structured ur model and what your use case it?

**Comment by alanent** [comment]
Your results are better than mine. I think the dataset need to be carried out on a more significant mass of fen. I collected human comments in open databases. I would like to test a rag system with your approach. Finetune an LLM could also interest me but the task seems more complex. I don't know if the introduction of a position evaluation of stockfish would be useful for the creation of embeddings? Looking forward to talking about it

**Comment by broskicodes** [comment]
i thought abt finetuning an LLM too. gathering and preprocessing data proved to be painful tho, so i stopped.

i spent a decent amnt of time thinking abt the problem tho.

happy to chat with you abt it sometime. here's my cal if u wanna book something: https://cal.com/braeden/coffee
